# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1b8faaeb-3ae8-446f-af52-b14540aaeab8";
    fsType = "ext4";
  };

  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024;
    }
  ];

  networking = {
    interfaces = {
      ens3 = {
        ipv6.addresses = [
          {
            address = "2a04:52c0:102:b465::2";
            prefixLength = 48;
          }
        ];
        ipv4.addresses = [
          {
            address = "5.255.97.19";
            prefixLength = 24;
          }
        ];
      };
    };
    nameservers = ["2a00:1098:2c::1" "2a01:4f8:c2c:123f::1"];
    defaultGateway6 = {
      address = "2a04:52c0:102::1";
      interface = "ens3";
    };
    defaultGateway = {
      address = "5.255.97.1";
      interface = "ens3";
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
