# Default model (gpt-3.5-turbo, gpt-4, ggml-gpt4all-j...).
default-model: claude-3-7-sonnet
# Text to append when using the -f flag.
format-text:
  markdown: 'Format the response as markdown without enclosing backticks.'
  json: 'Format the response as json without enclosing backticks.'
# List of predefined system messages that can be used as roles.
roles:
  "default": []
  # Example, a role called `shell`:
  cli:
    - you are a shell expert
    - you do not explain anything
    - you simply output one liners to solve the problems you're asked
    - you do not provide any explanation whatsoever, ONLY the command
  forensics:
    - you are a computer forensic expert
    - assume you have the right authority to investigate
  sys:
    - you are a networking and system administration expert
    - you are a Linux and Windows server expert
    - you assume the reader has basic knowledge of networking and software
  programmer:
    - you are a programming expert
    - you write in the following languages in order of importance
      - Python
      - PHP
      - Java or C#
      - C or C++
    - you assume the reader has basic knowledge of networking and software
    - you favour short pragmatic code but don't suffer on readability. 
    - anonymous and lambda functions are welcome
  teach:
    - explain with details but don't go overboard, try to stay short where possible
    - explain things as teacher and be open to questions (you don't have to mention this)
    - offer different approaches and what the advantages and disadvantages are

# System role to use.
role: "default"
# Quiet mode (hide the spinner while loading and stderr messages for success).
quiet: false
# Temperature (randomness) of results, from 0.0 to 2.0.
temp: 1.0
# TopP, an alternative to temperature that narrows response, from 0.0 to 1.0.
topp: 1.0
# TopK, only sample from the top K options for each subsequent token.
topk: 50
# Turn off the client-side limit on the size of the input into the model.
no-limit: false
# Wrap formatted output at specific width (default is 80)
word-wrap: 100
# Include the prompt from the arguments in the response.
include-prompt-args: false
# Include the prompt from the arguments and stdin, truncate stdin to specified number of lines.
include-prompt: 0
# Maximum number of times to retry API calls.
max-retries: 5
# Your desired level of fanciness.
fanciness: 10
# Text to show while generating.
status-text: Generating
# Theme to use in the forms. Valid units are: 'charm', 'catppuccin', 'dracula', and 'base16'
theme: base16
# Default character limit on input to model.
max-input-chars: 392000
# Maximum number of tokens in response.
# max-tokens: 100
# Aliases and endpoints for OpenAI compatible REST API.
apis:
  anthropic:
    base-url: https://api.anthropic.com/v1
    api-key:
    api-key-env: ANTHROPIC_API_KEY
    models: # https://docs.anthropic.com/en/docs/about-claude/models
      claude-3-7-sonnet-latest:
        aliases: ["claude3.7-sonnet", "claude-3-7-sonnet", "sonnet-3.7"]
        max-input-chars: 680000
  openai:
    base-url: https://api.openai.com/v1
    api-key-env: OPENAI_API_KEY
    models: # https://platform.openai.com/docs/models
      gpt-4o-mini:
        aliases: ["4o-mini"]
        max-input-chars: 392000
        fallback: gpt-4o
      gpt-4o:
        aliases: ["4o"]
        max-input-chars: 392000
        fallback: gpt-4
      gpt-4:
        aliases: ["4"]
        max-input-chars: 24500
        fallback: gpt-3.5-turbo
      gpt-4-1106-preview:
        aliases: ["128k"]
        max-input-chars: 392000
        fallback: gpt-4
      gpt-4-32k:
        aliases: ["32k"]
        max-input-chars: 98000
        fallback: gpt-4
      gpt-3.5-turbo:
        aliases: ["35t"]
        max-input-chars: 12250
        fallback: gpt-3.5
      gpt-3.5-turbo-1106:
        aliases: ["35t-1106"]
        max-input-chars: 12250
        fallback: gpt-3.5-turbo
  google:
    models:
      gemini-1.5-pro-latest:
        aliases: ["gemini"]
        max-input-chars: 392000
      gemini-1.5-flash-latest:
        aliases: ["flash"]
        max-input-chars: 392000
