# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
 imports =
   [ (modulesPath + "/installer/scan/not-detected.nix")
   ];

 boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod
" ];
 boot.initrd.kernelModules = [ ];
 boot.kernelModules = [ "kvm-intel" ];
 boot.extraModulePackages = [ ];

 fileSystems."/" =
   { device = "/dev/disk/by-uuid/208e3222-bbd0-4867-9245-4aa9ccb27b45";
     fsType = "ext4";
   };

 fileSystems."/boot" =
   { device = "/dev/disk/by-uuid/8FD7-2AF9";
     fsType = "vfat";
   };

 swapDevices =
   [ { device = "/dev/disk/by-uuid/416601b3-23c4-4169-9d99-37bae9898e66"; }
   ];

 # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
 # (the default) this is the recommended approach. When using systemd-networkd it's
 # still possible to use this option, but it's recommended to use it in conjunction
 # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
 networking.useDHCP = lib.mkDefault true;
 # networking.interfaces.enp114s0.useDHCP = lib.mkDefault true;
 # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

 nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
 hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
